import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';

import { slackFileFromRaw } from '../slack/slack.helper.js';
import { safeFilename } from '../storage/safe-filename.js';
import { MANUAL_FETCH_BYTES, downloadSlackFile } from '../slack/slack-file.service.js';

test('manual Slack file fetch allows large user-requested downloads', () => {
  assert.ok(MANUAL_FETCH_BYTES >= 500 * 1024 * 1024);
});

test('slackFileFromRaw extracts known fields and prefers download URL', () => {
  const file = slackFileFromRaw({
    id: 'F1',
    name: 'screenshot.png',
    mimetype: 'image/png',
    size: 1024,
    url_private: 'https://files.slack.com/private',
    url_private_download: 'https://files.slack.com/download',
  });
  assert.equal(file?.id, 'F1');
  assert.equal(file?.name, 'screenshot.png');
  assert.equal(file?.mimetype, 'image/png');
  assert.equal(file?.sizeBytes, 1024);
  assert.equal(file?.urlPrivate, 'https://files.slack.com/download');
});

test('safeFilename strips path separators and falls back to "file"', () => {
  assert.equal(safeFilename('foo/bar.txt'), 'foo_bar.txt');
  assert.equal(safeFilename(''), 'file');
  assert.equal(safeFilename('   '), 'file');
});

test('downloadSlackFile writes the response body and honors Bearer auth + size cap', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'anima-files-'));
  try {
    const destPath = join(dir, 'cache/F1/data.txt');
    const seen: { url?: string; auth?: string } = {};
    const fetchImpl = (async (url: string, init?: { headers?: Record<string, string> }) => {
      seen.url = url;
      seen.auth = init?.headers?.['Authorization'];
      const body = Buffer.from('hello');
      return new Response(body, { status: 200, headers: { 'content-length': String(body.length) } });
    }) as unknown as typeof fetch;
    const result = await downloadSlackFile({
      destPath,
      fetchImpl,
      maxBytes: 1024,
      token: 'xoxb-token',
      urlPrivate: 'https://files.slack.com/example',
    });
    assert.equal(result.sizeBytes, 5);
    assert.equal(seen.url, 'https://files.slack.com/example');
    assert.equal(seen.auth, 'Bearer xoxb-token');
    assert.equal(await readFile(destPath, 'utf8'), 'hello');

    const oversized = (async () => new Response(Buffer.from('xxxxxxxxxxxxx'), {
      status: 200,
      headers: { 'content-length': '13' },
    })) as unknown as typeof fetch;
    await assert.rejects(
      downloadSlackFile({
        destPath: join(dir, 'cache/F2/data.txt'),
        fetchImpl: oversized,
        maxBytes: 4,
        token: 't',
        urlPrivate: 'https://x',
      }),
      /too large/,
    );

    const failing = (async () => new Response('nope', {
      status: 403,
      statusText: 'Forbidden',
    })) as unknown as typeof fetch;
    await assert.rejects(
      downloadSlackFile({
        destPath: join(dir, 'cache/F3/data.txt'),
        fetchImpl: failing,
        maxBytes: 1024,
        token: 't',
        urlPrivate: 'https://x',
      }),
      /HTTP 403/,
    );
  } finally {
    await rm(dir, { force: true, recursive: true });
  }
});

test('downloadSlackFile rejects when streamed body exceeds maxBytes despite missing content-length', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'anima-files-'));
  try {
    const fetchImpl = (async () => new Response(Buffer.from('x'.repeat(100)), { status: 200, headers: {} })) as unknown as typeof fetch;
    await assert.rejects(
      downloadSlackFile({
        destPath: join(dir, 'F1/data.bin'),
        fetchImpl,
        maxBytes: 10,
        token: 't',
        urlPrivate: 'https://x',
      }),
      /too large/,
    );
  } finally {
    await rm(dir, { force: true, recursive: true });
  }
});

// Sanity-check that fixtures generated by Slack don't disappear when we round-trip them
test('writeFile + downloadSlackFile roundtrip with a temp source url is consistent', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'anima-files-'));
  try {
    const source = join(dir, 'source.txt');
    await writeFile(source, 'roundtrip\n');
    const fetchImpl = (async () => new Response(await readFile(source), { status: 200, headers: { 'content-length': '10' } })) as unknown as typeof fetch;
    const destPath = join(dir, 'cache/F9/data.txt');
    const result = await downloadSlackFile({
      destPath,
      fetchImpl,
      maxBytes: 1024,
      token: 't',
      urlPrivate: 'https://x',
    });
    assert.equal(result.sizeBytes, 10);
    assert.equal(await readFile(destPath, 'utf8'), 'roundtrip\n');
  } finally {
    await rm(dir, { force: true, recursive: true });
  }
});
